os: osx
language: r
latex: false
pandoc: false
fortran: false
disable_homebrew: true
sudo: required

matrix:
  include:
    - osx_image: xcode9.4
    - osx_image: xcode7.3
      before_script:
        - sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

before_install:
  - sudo networksetup -setdnsservers Ethernet 1.1.1.1

install:
  R -e 'install.packages("gh")'

script:
  - Rscript testcran.R

branches:
  only:
  - gh-pages
