on:
#  push:
  workflow_dispatch:

name: Check all the packages

jobs:
  macos:

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-10.15', 'macos-11.0']
    steps:
      - uses: actions/checkout@v2

      - name: install R
        run: brew cask install r gfortran

      - name: Remove homebrew
        run: |
          curl -fsSOL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
          sudo /bin/bash uninstall.sh --force
          rm uninstall.sh
          hash -r

      - name: run check script
        run: |
          mkdir fakehome
          cp ~/.gitconfig fakehome/ || touch fakehome/.gitconfig
          chmod 500 fakehome
          HOME="$PWD/fakehome" PATH="$PATH:/Library/Frameworks/R.framework/Resources/bin" Rscript fullcheck.R
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
